
## Cluster Module Outputs
output "cluster_id" {
  value       = module.rosa_cluster_hcp.cluster_id
  description = "Unique identifier of the cluster."
}

output "cluster_admin_username" {
  value       = module.rosa_cluster_hcp.cluster_admin_username
  description = "The username of the admin user."
}

output "cluster_admin_password" {
  value       = module.rosa_cluster_hcp.cluster_admin_password
  description = "The password of the admin user."
  sensitive   = true
}

output "cluster_api_url" {
  value       = module.rosa_cluster_hcp.cluster_api_url
  description = "The URL of the API server."
}

output "cluster_console_url" {
  value       = module.rosa_cluster_hcp.cluster_console_url
  description = "The URL of the console."
}

output "cluster_domain" {
  value       = module.rosa_cluster_hcp.cluster_domain
  description = "The DNS domain of cluster."
}

output "cluster_current_version" {
  value       = module.rosa_cluster_hcp.cluster_current_version
  description = "The currently running version of OpenShift on the cluster, for example '4.11.0'."
}

output "cluster_state" {
  value       = module.rosa_cluster_hcp.cluster_state
  description = "The state of the cluster."
}

## Account Roles Module Outputs

output "account_role_prefix" {
  value       = var.create_account_roles ? module.account_iam_resources[0].account_role_prefix : null
  description = "The prefix used for all generated AWS resources."
}

output "account_roles_arn" {
  value       = var.create_account_roles ? module.account_iam_resources[0].account_roles_arn : null
  description = "A map of Amazon Resource Names (ARNs) associated with the AWS IAM roles created. The key in the map represents the name of an AWS IAM role, while the corresponding value represents the associated Amazon Resource Name (ARN) of that role."
}

output "path" {
  value       = var.create_account_roles ? module.account_iam_resources[0].path : null
  description = "The arn path for the account/operator roles as well as their policies."
}

## Oidc Config and Provider module Outputs

output "oidc_config_id" {
  value       = var.create_oidc ? module.oidc_config_and_provider[0].oidc_config_id : null
  description = "The unique identifier associated with users authenticated through OpenID Connect (OIDC) generated by this OIDC config."
}

output "oidc_endpoint_url" {
  value       = var.create_oidc ? module.oidc_config_and_provider[0].oidc_endpoint_url : null
  description = "Registered OIDC configuration issuer URL, generated by this OIDC config."
}

## Operator Roles Module Outputs

output "operator_role_prefix" {
  value       = var.create_operator_roles ? module.operator_roles[0].operator_role_prefix : null
  description = "Prefix used for generated AWS operator policies."
}

output "operator_roles_arn" {
  value       = var.create_operator_roles ? module.operator_roles[0].operator_roles_arn : null
  description = "List of Amazon Resource Names (ARNs) for all operator roles created."
}
