output "cluster_id" {
  value       = module.rosa_cluster_hcp.cluster_id
  description = "Unique identifier of the cluster."
}

output "cluster_admin_username" {
  value       = module.rosa_cluster_hcp.cluster_admin_username
  description = "The username of the admin user."
}

output "cluster_admin_password" {
  value       = module.rosa_cluster_hcp.cluster_admin_password
  description = "The password of the admin user."
  sensitive   = true
}

output "account_role_prefix" {
  value       = var.create_account_roles ? module.account_iam_resources[0].account_role_prefix: null
  description = "The prefix used for all generated AWS resources."
}

output "account_roles_arn" {
  value       = var.create_account_roles ? module.account_iam_resources[0].account_roles_arn: null
  description = "A map of Amazon Resource Names (ARNs) associated with the AWS IAM roles created. The key in the map represents the name of an AWS IAM role, while the corresponding value represents the associated Amazon Resource Name (ARN) of that role."
}

output "path" {
  value       = var.create_account_roles ? module.account_iam_resources[0].path: null
  description = "The arn path for the account/operator roles as well as their policies."
}

output "oidc_config_id" {
  value       = var.create_oidc ? module.oidc_config_and_provider[0].oidc_config_id: null
  description = "The unique identifier associated with users authenticated through OpenID Connect (OIDC) generated by this OIDC config."
}

output "oidc_endpoint_url" {
  value       = var.create_oidc ? module.oidc_config_and_provider[0].oidc_endpoint_url: null
  description = "Registered OIDC configuration issuer URL, generated by this OIDC config."
}

output "operator_role_prefix" {
  value       = var.create_operator_roles ? module.operator_roles[0].operator_role_prefix: null
  description = "Prefix used for generated AWS operator policies."
}

output "operator_roles_arn" {
  value       = var.create_operator_roles ? module.operator_roles[0].operator_roles_arn: null
  description = "List of Amazon Resource Names (ARNs) for all operator roles created."
}
