output "cluster_id" {
  value       = module.hcp.cluster_id
  description = "Unique identifier of the cluster."
}

output "account_role_prefix" {
  value       = module.hcp.account_role_prefix
  description = "The prefix used for all generated AWS resources."
}

output "account_roles_arn" {
  value       = module.hcp.account_roles_arn
  description = "A map of Amazon Resource Names (ARNs) associated with the AWS IAM roles created. The key in the map represents the name of an AWS IAM role, while the corresponding value represents the associated Amazon Resource Name (ARN) of that role."
}

output "path" {
  value       = module.hcp.path
  description = "The arn path for the account/operator roles as well as their policies."
}

output "oidc_config_id" {
  value       = module.hcp.oidc_config_id
  description = "The unique identifier associated with users authenticated through OpenID Connect (OIDC) generated by this OIDC config."
}

output "oidc_endpoint_url" {
  value       = module.hcp.oidc_endpoint_url
  description = "Registered OIDC configuration issuer URL, generated by this OIDC config."
}

output "operator_role_prefix" {
  value       = module.hcp.operator_role_prefix
  description = "Prefix used for generated AWS operator policies."
}

output "operator_roles_arn" {
  value       = module.hcp.operator_roles_arn
  description = "List of Amazon Resource Names (ARNs) for all operator roles created."
}

output "password" {
  value     = resource.random_password.password
  sensitive = true
}

output "client_id" {
  value     = resource.random_password.client_id
  sensitive = true
}

output "client_secret" {
  value     = resource.random_password.client_secret
  sensitive = true
}